### ISSUE TITLE
Unable to install on 1.9.3

### ISSUE THREAD

**Issue by johntdyer** [neillturner/ec2dream#1]
Having a bitch of a time getting this working on OSX 10.7.2

    22:53:13 (production_ec2) jdyer@aleph.local ec2dream master gem install ec2dream-3.2.5.gem
Building native extensions.  This could take a while...
ERROR:  Error installing ec2dream-3.2.5.gem:
	ERROR: Failed to build gem native extension.

        /Users/jdyer/.rvm/rubies/ruby-1.9.3-p194/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jdyer/.rvm/rubies/ruby-1.9.3-p194/bin/ruby
	--with-fox-dir
	--without-fox-dir
	--with-fox-include
	--without-fox-include=${fox-dir}/include
	--with-fox-lib
	--without-fox-lib=${fox-dir}/lib
	--with-fxscintilla-dir
	--without-fxscintilla-dir
	--with-fxscintilla-include
	--without-fxscintilla-include=${fxscintilla-dir}/include
	--with-fxscintilla-lib
	--without-fxscintilla-lib=${fxscintilla-dir}/lib
extconf.rb:31:in `find_installed_fox_version': couldn't find FOX header files (RuntimeError)
	from extconf.rb:133:in `<main>'

Is this only compatible with a certain version of Ruby or in a certain environment ?

**Comment by blacksun1** [comment]
I was able to get fox to install on my Mac OSX Yosemite by using trial and error and in the end brew came to my rescue

```
brew tap homebrew/x11
brew install fox
```

**Comment by neillturner** [comment]
closing. updated by install web page.
