### ISSUE TITLE
Problem connecting to OpenStack

### ISSUE THREAD

**Issue by foss-guy** [neillturner/ec2dream#2]
Thanks for publishing this tool!

I used the instructions for Jaunty as a guide and managed to get ec2dream running on Ubuntu 11.10. But I was unable to connect to an OpenStack instance I'd set up on Ubuntu 12.04.
In the console which I started ec2dream I get:

Settings.load
Settings.load_panel EC2_PLATFORM
Settings.load_panel KEYPAIR_NAME
Settings.load_panel EC2_URL
Settings.load_panel EC2_SSH_PRIVATE_KEY
Settings.load_panel AMAZON_ACCOUNT_ID
Settings.load_panel AMAZON_ACCESS_KEY_ID
Settings.load_panel AMAZON_SECRET_ACCESS_KEY
Settings.load_panel CHEF_REPOSITORY
Settings.load_panel RDS_URL
Settings.load_panel AMAZON_NICKNAME_TAG
Settings.load_panel CLOUD_ADMIN_URL
ServerCache.ops_refreshServerStackTree
environment.connection
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/server.rb:36: warning: method redefined; discarding old metadata
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/server.rb:45: warning: method redefined; discarding old metadata=
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/server.rb:96: warning: method redefined; discarding old image_ref=
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/server.rb:104: warning: method redefined; discarding old flavor_ref=
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/image.rb:28: warning: method redefined; discarding old metadata
/var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/models/compute/image.rb:37: warning: method redefined; discarding old metadata=
***Error on connection to OpenStack - check your keys in environment.connection

When you tested, did you generate EC2 style credentials in OpenStack and pass those in ec2dream? I tried both EC2 style credentials and just the OpenStack user name and password, but the same error results.

Comparing /var/lib/gems/1.8/gems/fog-1.3.1/lib/fog/openstack/compute.rb and var/lib/gems/1.8/gems/ec2dream-3.3.0/lib/EC2_Environment.rb, the fog class seems to have more parameters than passed from ec2dream. I did try the following changes (lines 380-383), but it didn't help. I put .... below in the values though they are from a test installation
just for the purposes of this post - when running the tool I used the actual complete strings.
    370     if settings.get("EC2_PLATFORM") == "openstack"^M 
    371        begin^M 
    372           puts "openstack_auth_url will be #{settings.get('EC2_URL')}" 
    373           puts "openstack_api_key will be #{settings.get('AMAZON_SECRET_ACCESS_KEY')}" 
    374           puts "openstack_username will be #{settings.get('AMAZON_ACCESS_KEY_ID')}" 
    375           @ec2 = Fog::Compute.new({:provider => 'OpenStack',^M 
    376             :openstack_auth_url => settings.get('EC2_URL'), ^M 
    377             :openstack_api_key => settings.get('AMAZON_SECRET_ACCESS_KEY'),  ^M 
    378             :openstack_username => settings.get('AMAZON_ACCESS_KEY_ID'), 
    379             # })            ^M 
    380             :openstack_tenant => 'b18fe...', 
    381             :openstack_compute_service_name => 'nova', 
    382             :openstack_management_url => 'http://172.10....:8773/services/Cloud', 
    383             :openstack_auth_token => '9998.....'})

Can you please resolve this or provide inputs so I can?

**Comment by neillturner** [comment]
openstack is working at least on windows
