### ISSUE TITLE
Local servers port number not set correctly.

### ISSUE THREAD

**Issue by blacksun1** [neillturner/ec2dream#5]
Hi Neill,

On the "Local Servers" configuration screen, the field "Local Port" which is under "Bastian Host" is being used as the standard putty port number rather than "Address Port".

**How to Reproduce**

1. Create a new Environment of type "Server".
1. Click on "Local Server"
2. Click "new" button
3. Fill in the following:
    Server = "server"
    Address = "localhost"
    Address Port = 2222
    ssh user = "user"
4. Hit save
5 Hit the SSH button.
6. Check the console for the executed command. It will not include "-P 2222" as should be expected.

**Workaround**

Enter the port number (2222) in the "Local Port" field which is under "Tunnelling - Bastian Host" instead.

**Comment by neillturner** [comment]
coded this but still need to test
